# Generated by Django 2.2.4 on 2022-08-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='watchers',
        ),
        migrations.DeleteModel(
            name='IssueWatcher',
        ),
    ]
