# Generated by Django 2.2.4 on 2022-08-08 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0002_auto_20220808_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='watchers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
