# Generated by Django 2.2.4 on 2022-08-10 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0002_auto_20220810_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueWatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropship.Issue')),
                ('watcher', models.ForeignKey(db_column='watchers', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='watchers',
            field=models.ManyToManyField(blank=True, through='dropship.IssueWatcher', to=settings.AUTH_USER_MODEL),
        ),
    ]
