# Generated by Django 2.2.4 on 2022-08-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0003_auto_20220808_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(blank=True, default='open', max_length=30, null=True),
        ),
    ]
