# Generated by Django 2.2.4 on 2022-08-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0004_auto_20220808_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
    ]
