# Generated by Django 2.2.4 on 2022-08-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0005_auto_20220805_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('InProgress', 'InProgress'), ('InReview', 'InReview'), ('CodeComplete', 'CodeComplete'), ('QA Testing', 'QA Testing'), ('Done', 'Done')], default='Open', max_length=20),
        ),
    ]
