# Generated by Django 2.2.4 on 2022-08-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0005_remove_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('in progress', 'in progress'), ('under Review', 'under Review'), ('code complete ', 'code complete '), ('qa testing', 'qa testing'), ('done', 'done')], default='open', max_length=30),
        ),
    ]
