# Generated by Django 2.2.4 on 2022-08-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0006_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('in progress', 'in progress'), ('in review', 'in review'), ('code complete ', 'code complete '), ('qa testing', 'qa testing'), ('done', 'done')], default='open', max_length=30),
        ),
    ]
