# Generated by Django 2.2.4 on 2022-08-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0007_auto_20220806_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
