# Generated by Django 2.2.4 on 2022-08-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0009_issue_label_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='label_list',
            new_name='labels_list',
        ),
    ]
