# Generated by Django 2.2.4 on 2022-08-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0011_auto_20220808_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='watchers_list',
            field=models.ManyToManyField(blank=True, null=True, to='dropship.Member'),
        ),
    ]
