# Generated by Django 2.2.4 on 2022-08-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0012_issue_watchers_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_time', models.CharField(max_length=10)),
                ('time_spent', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='time_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dropship.TimeLog'),
        ),
    ]
