# Generated by Django 2.2.4 on 2022-08-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0013_auto_20220808_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='time_log',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='dropship.Project'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint', to='dropship.Sprint'),
        ),
    ]
